# Generated by Django 4.2.5 on 2023-09-16 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("donation", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="donation",
            name="country",
        ),
        migrations.RemoveField(
            model_name="donation",
            name="email_address",
        ),
        migrations.RemoveField(
            model_name="donation",
            name="phone_number",
        ),
        migrations.RemoveField(
            model_name="donation",
            name="remarks",
        ),
        migrations.CreateModel(
            name="Donor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "email_address",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("country", models.CharField(max_length=100)),
                ("remarks", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "referred_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="donation.donor",
                        verbose_name="Referred By",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Donors",
            },
        ),
        migrations.AddField(
            model_name="donation",
            name="donor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="donations",
                to="donation.donor",
                verbose_name="Donor Name",
            ),
        ),
    ]
